local UI = require("ui2d")

return UI.StyleSheet {
    viewport = {
        reference_width = 1100,
        reference_height = 720,
        min_scale = 0.68,
        max_scale = 2,
    },
    colors = {
        transparent = {0, 0, 0, 0},
        veil = {0.012, 0.016, 0.025, 0.92},
        panel = {0.045, 0.057, 0.082, 0.985},
        panel_soft = {0.075, 0.092, 0.128, 0.94},
        line = {0.24, 0.34, 0.46, 0.42},
        accent = {0.16, 0.90, 1.00, 1},
        accent_soft = {0.16, 0.90, 1.00, 0.14},
        segment_fill = {0.075, 0.18, 0.22, 1},
        ink = {0.018, 0.035, 0.045, 1},
        text = {0.92, 0.96, 1.00, 1},
        muted = {0.54, 0.63, 0.73, 1},
        white = {1, 1, 1, 1},
    },
    text = {
        display = {size = 30, color = "text"},
        title = {size = 22, color = "text"},
        body = {size = 16, color = "text"},
        binding = {size = 15, color = "accent"},
        label = {size = 12, color = "muted"},
        small = {size = 13, color = "muted"},
        hud_title = {size = 20, color = "text"},
        hud = {size = 13, color = "muted"},
    },
    buttons = {
        binding = {
            background = "panel_soft",
            foreground = "text",
            min_height = 48,
            padding_x = 16,
            padding_y = 10,
            radius = 7,
            text = "body",
            transform = {translate_x = 0, scale = 1},
            states = {
                highlighted = {
                    background = "accent_soft",
                    border = "accent",
                    transform = {translate_x = 5, scale = 1},
                },
                hovered = "highlighted",
                selected = "highlighted",
                pressed = {
                    background = "accent_soft",
                    transform = {translate_x = 2, scale = 0.99},
                },
            },
            transition = {transform = {duration = 0.13, ease = "out_cubic"}},
        },
        resume = {
            background = "accent",
            foreground = "ink",
            min_height = 44,
            padding_x = 20,
            padding_y = 9,
            radius = 7,
            text = "body",
            transform = {scale = 1},
            states = {
                hovered = {transform = {scale = 1.035}},
                selected = {transform = {scale = 1.035}},
                pressed = {transform = {scale = 0.97}},
            },
            transition = {transform = {duration = 0.12, ease = "out_cubic"}},
        },
        segment = {
            background = "transparent",
            foreground = "muted",
            min_height = 40,
            padding_x = 12,
            padding_y = 8,
            radius = 5,
            text = "small",
            states = {
                hovered = {foreground = "text"},
                selected = {foreground = "text", focus = "accent"},
                pressed = {transform = {scale = 0.97}},
            },
        },
        segment_active = {
            background = "transparent",
            foreground = "accent",
            min_height = 40,
            padding_x = 12,
            padding_y = 8,
            radius = 5,
            text = "small",
            states = {
                hovered = {foreground = "text"},
                selected = {foreground = "accent", focus = "accent"},
                pressed = {transform = {scale = 0.97}},
            },
        },
    },
}
