local UI = require("ui2d")

return UI.StyleSheet {
    viewport = {
        reference_width = 960,
        reference_height = 640,
        min_scale = 0.75,
        max_scale = 2,
    },
    colors = {
        world = {0.025, 0.04, 0.065, 1},
        overlay = {0.035, 0.045, 0.075, 0.97},
        panel = {0.09, 0.11, 0.17, 1},
        tooltip = {0.13, 0.15, 0.22, 1},
        accent = {0.95, 0.31, 0.23, 1},
        white = {0.96, 0.97, 1, 1},
        ink = {0.12, 0.09, 0.07, 1},
        parchment = {0.94, 0.90, 0.76, 1},
        parchment_border = {0.58, 0.43, 0.24, 1},
        card_light = {1, 0.96, 1, 1},
        card_muted = {0.90, 0.82, 0.91, 1},
    },
    text = {
        title = {font = "default", size = 28, color = "white"},
        body = {font = "default", size = 17, color = "white"},
        card_title = {font = "default", size = 22, color = "card_light"},
        card_body = {font = "default", size = 14, color = "card_muted"},
        paper_title = {font = "default", size = 22, color = "ink"},
        paper_title_inverse = {font = "default", size = 22, color = "parchment"},
        paper_body = {font = "default", size = 14, color = "ink"},
    },
    buttons = {
        motion = {
            background = "accent",
            foreground = "white",
            min_width = 190,
            min_height = 48,
            padding_x = 18,
            padding_y = 10,
            text = "body",
            transform = {translate_y = 0, scale = 1},
            states = {
                highlighted = {transform = {translate_y = -5, scale = 1.03}},
                hovered = "highlighted",
                selected = "highlighted",
                pressed = {transform = {translate_y = 0, scale = 0.97}},
            },
            transition = {
                transform = {duration = 0.16, ease = "out_cubic"},
            },
        },
        drawer_handle = {
            background = "tooltip",
            background_hovered = {0.20, 0.23, 0.32, 1},
            background_pressed = {0.26, 0.29, 0.38, 1},
            foreground = "white",
            min_width = 168,
            min_height = 26,
            padding_x = 18,
            padding_y = 3,
            radius = 13,
            text = "card_body",
        },
    },
}
